Resources:
  StoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: storyId
          AttributeType: S
        - AttributeName: text
          AttributeType: S
      KeySchema:
        - AttributeName: storyId
          KeyType: HASH
        - AttributeName: text
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}